config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  resource :session
  resources :passwords, param: :token
  resources :organizations
  resources :matches do
    member do
      patch :submit_match_result
    end
  end
  resources :machines
  resources :users
  resources :rounds
  resources :seasons
  resources :registrations, only: %i[ new create ]
  resources :memberships, only: %i[ new create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id              :bigint           not null, primary key
#  title           :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint
#
# Indexes
#
#  index_seasons_on_organization_id  (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#

class Season < ApplicationRecord
  has_many :rounds
  belongs_to :organization
  validates_presence_of :title

  def ordered_rounds
    rounds.order(:number)
  end

  def form_round_number
    ordered_rounds.blank? ? 1 : ordered_rounds.last.number + 1
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: %i[ show edit update destroy ]

  # GET /seasons or /seasons.json
  def index
    @seasons = Season.where(organization: Current.user.current_organization)
  end

  # GET /seasons/1 or /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons or /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        GenerateLeague.call(season: @season, number_of_rounds: rounds_params[:number_of_rounds].to_i)
        format.html { redirect_to @season, notice: "Season was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_content }
        format.turbo_stream
      end
    end
  end

  # PATCH/PUT /seasons/1 or /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: "Season was successfully updated." }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_content }
        format.turbo_stream
      end
    end
  end

  # DELETE /seasons/1 or /seasons/1.json
  def destroy
    @season.destroy!

    respond_to do |format|
      format.html { redirect_to seasons_path, status: :see_other, notice: "Season was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def season_params
      params.expect(season: [ :title, :organization_id ])
    end
    def rounds_params
      params.expect(season: [ :number_of_rounds ])
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_with(model: season) do |form| %>
  <% if season.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
        <% season.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :organization_id, value: Current.user.current_organization_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :number_of_rounds, style: "display: block" %>
    <%= form.number_field :number_of_rounds %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/_new_round_button.html.erb
<%# locals: (season:)  %>

<%= button_to 'Create a new Round', rounds_path, params: { round: { season_id: season.id, number: season.form_round_number } }, data: { turbo_stream: true } %>

app/views/seasons/_new_season_link.html.erb
<%= link_to "New season", new_season_path, data: { turbo_stream: true } %>

app/views/seasons/_season.html.erb
<%# locals: (season:) %>

<div id="<%= dom_id season %>">
  <p>
    <strong>Title:</strong>
    <%= link_to "#{season.title}", season_path(season) %>
    <%= link_to 'Edit', edit_season_path(season), data: { turbo_stream: true } %>
    <%= link_to 'Delete', season_path(season), data: { turbo_method: :delete } %>
  </p>
</div>

app/views/seasons/create.turbo_stream.erb
<% if @season.errors.present? %>
  <%= turbo_stream.update 'new_season', partial: 'seasons/form', locals: { season: @season } %>
<% else %>
  <%= turbo_stream.update 'new_season', partial: 'seasons/new_season_link' %>
  <%= turbo_stream.prepend 'seasons', partial: 'seasons/season', locals: { season: @season } %>
<% end %>

app/views/seasons/edit.html.erb
<% content_for :title, "Editing season" %>

<h1>Editing season</h1>

<%= render "form", season: @season %>

<br>

<div>
  <%= link_to "Show this season", @season %> |
  <%= link_to "Back to seasons", seasons_path %>
</div>

app/views/seasons/edit.turbo_stream.erb
<%= turbo_stream.update @season, partial: 'seasons/form', locals: { season: @season } %>

app/views/seasons/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Seasons" %>

<h1>Seasons</h1>

<%= turbo_frame_tag 'new_season' do %>
    <%= render partial: 'seasons/new_season_link' %>
<% end %>

<div id="seasons">
  <% @seasons.each do |season| %>
    <%= render season %>
  <% end %>
</div>

app/views/seasons/new.html.erb
<% content_for :title, "New season" %>

<h1>New season</h1>

<%= render "form", season: @season %>

<br>

<div>
  <%= link_to "Back to seasons", seasons_path %>
</div>

app/views/seasons/new.turbo_stream.erb
<%= turbo_stream.update 'new_season', partial: 'seasons/form', locals: { season: @season } %>

app/views/seasons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @season %>

<div>
  <%#= turbo_frame_tag 'new_round' do %>
    <%#= render partial: 'seasons/new_round_button', locals: { season: @season }  %>
  <%# end %>

  <h2>
    Rounds
  </h2>
  <%= turbo_frame_tag "season_#{@season.id}_rounds" do %>
    <%= render partial: 'rounds/rounds', locals: { rounds: @season.ordered_rounds } %>
  <% end %>
</div>

app/views/seasons/update.turbo_stream.erb
<% if @season.errors.present? %>
  <%= turbo_stream.update @season, partial: 'seasons/form', locals: { season: @season } %>
<% else %>
  <%= turbo_stream.update @season, partial: 'seasons/season', locals: { season: @season } %>
<% end %>