config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  resource :session
  resources :passwords, param: :token
  resources :organizations
  resources :matches do
    member do
      patch :submit_match_result
    end
  end
  resources :machines
  resources :users
  resources :rounds
  resources :seasons
  resources :registrations, only: %i[ new create ]
  resources :memberships, only: %i[ new create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    authorize Current.user, policy_class: HomePolicy

    if Current.user.current_organization_id.present?
      redirect_to dashboard_path
    end
  end
end

app/views/home/dashboard.html.erb
<h1><%= @organization.name %></h1>
<h2><%= @organization.code %></h2>
<%= link_to 'Seasons', seasons_path %>
<%= link_to 'Machines', machines_path %>
<%= link_to 'Users', users_path %>

app/views/home/index.html.erb
<% if alert = flash[:alert] %>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
<% end %>

<% if notice = flash[:notice] %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

<h1>Pinbowl Wizard Home Page</h1>

<div>
  <%= link_to "Create Organization", new_organization_path %>
</div>

<div>
  <%= link_to "Join Organization", new_membership_path %>
</div>