config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  resource :session
  resources :passwords, param: :token
  resources :organizations
  resources :matches do
    member do
      patch :submit_match_result
    end
  end
  resources :machines
  resources :users
  resources :rounds
  resources :seasons
  resources :registrations, only: %i[ new create ]
  resources :memberships, only: %i[ new create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  flight_id  :bigint           not null
#  machine_id :bigint           not null
#
# Indexes
#
#  index_matches_on_flight_id   (flight_id)
#  index_matches_on_machine_id  (machine_id)
#
# Foreign Keys
#
#  fk_rails_...  (flight_id => flights.id)
#  fk_rails_...  (machine_id => machines.id)
#

class Match < ApplicationRecord
  belongs_to :flight
  belongs_to :machine
  has_many :player_matches
  has_many :users, through: :player_matches
  accepts_nested_attributes_for :player_matches
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy submit_match_result ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @match.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @match.errors, status: :unprocessable_content }
      end
    end
  end

  def submit_match_result
    CalculateMatchResults.call(player_matches: format_player_match_params(match_player_match_params[:player_matches_attributes]))
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy!

    respond_to do |format|
      format.html { redirect_to matches_path, status: :see_other, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.expect(match: [ :id, :flight_id, :machine_id ])
    end

    def match_player_match_params
      params.expect(match: [ :id, :flight_id, :machine_id, player_matches_attributes: [ [ :id, :score, :user_id ] ] ])
    end

    def format_player_match_params(params)
      {
        player_1: {
          id: params["0"][:id].to_i,
          user_id: params["0"][:user_id].to_i,
          score: params["0"][:score].to_i
        },
        player_2: {
          id: params["1"][:id].to_i,
          user_id: params["1"][:user_id].to_i,
          score: params["1"][:score].to_i
        }
      }
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :round_id, style: "display: block" %>
    <%= form.text_field :round_id %>
  </div>

  <div>
    <%= form.label :machine_id, style: "display: block" %>
    <%= form.text_field :machine_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<%# locals: (match:) %>

<div id="<%= dom_id match %>">
  <p>
    <strong>Machine:</strong>
    <%= match.machine.name %>
  </p>

  <p>
    <strong>Players:</strong>

    <%= form_with model: match, url: submit_match_result_match_path(match), method: :patch do |form| %>
      <%= form.hidden_field :id %>
      <%= form.hidden_field :machine_id %>
      <%= form.hidden_field :flight_id %>
      <%= form.fields_for :player_matches do |match_form| %>
        <p>
          <%= "#{match_form.object.user&.first_name} #{match_form.object.user&.last_name}" %>
          <%= match_form.hidden_field :user_id %>
          <%= match_form.label :score %>
          <%= match_form.number_field :score %>
        </p>
      <% end %>
      <%= form.submit 'Submit' %>
    <% end %>
  </p>
</div>

app/views/matches/_player_match_form.html.erb
<%# locals: (match_form:, player_match:) %>

<div id= "<%= dom_id player_match %>">
  <p>
    <%= player_match.user.first_name %>
    <%= match_form.hidden_field :player_id, value: player_match.user_id %>
    <%= match_form.label :score %>
    <%= match_form.number_field :score %>
  </p>
</div>

app/views/matches/_player_matches_form.html.erb
<%# locals: (match_form:, player_matches:) %>

<div id= <%= "match_#{match_form.object_id}_player_matches" %>>
  <% player_matches.each do |player_match| %>
    <%= render partial: 'matches/player_match_form', locals: { match_form: match_form, player_match: player_match } %>
  <% end %>
</div>

app/views/matches/edit.html.erb
<% content_for :title, "Editing match" %>

<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Matches" %>

<h1>Matches</h1>

<div id="matches">
  <% @matches.each do |match| %>
    <%= render match %>
    <p>
      <%= link_to "Show this match", match %>
    </p>
  <% end %>
</div>

<%= link_to "New match", new_match_path %>

app/views/matches/new.html.erb
<% content_for :title, "New match" %>

<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

<div>
  <%= link_to "Edit this match", edit_match_path(@match) %> |
  <%= link_to "Back to matches", matches_path %>

  <%= button_to "Destroy this match", @match, method: :delete %>
</div>

app/views/matches/submit_match_result.turbo_stream.erb
<%= turbo_stream.update dom_id(@match), partial: 'matches/match', locals: { match: @match } %>