config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "dashboard", to: "home#dashboard", as: "dashboard"
  resource :session
  resources :passwords, param: :token
  resources :organizations
  resources :matches do
    member do
      patch :submit_match_result
    end
  end
  resources :machines
  resources :users
  resources :rounds
  resources :seasons
  resources :registrations, only: %i[ new create ]
  resources :memberships, only: %i[ new create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/machine.rb
# == Schema Information
#
# Table name: machines
#
#  id              :bigint           not null, primary key
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint           not null
#
# Indexes
#
#  index_machines_on_organization_id  (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#

class Machine < ApplicationRecord
  has_many :matches
  belongs_to :organization

  validates :name, presence: true
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: %i[ show edit update destroy ]

  # GET /machines or /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1 or /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines or /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to machines_path, notice: "Machine was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_content }
        format.turbo_stream
      end
    end
  end

  # PATCH/PUT /machines/1 or /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: "Machine was successfully updated." }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_content }
        format.turbo_stream
      end
    end
  end

  # DELETE /machines/1 or /machines/1.json
  def destroy
    @machine.destroy!

    respond_to do |format|
      format.html { redirect_to machines_path, status: :see_other, notice: "Machine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def machine_params
      params.expect(machine: [ :name, :organization_id ])
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_with(model: machine) do |form| %>
  <% if machine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
        <% machine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<div id="<%= dom_id machine %>">
  <p>
    <strong>Name:</strong>
    <%= machine.name %>
    <%= link_to 'Edit', edit_machine_path(machine), data: { turbo_stream: true } %>
    <%= link_to 'Delete', machine_path(machine), data: { turbo_method: :delete } %>
  </p>

</div>

app/views/machines/_new_machine_link.html.erb
<%= link_to 'New Machine', new_machine_path, data: { turbo_stream: 'new_machine' } %>

app/views/machines/create.turbo_stream.erb
<% if @machine.errors.present? %>
  <%= turbo_stream.update 'new_machine', partial: 'machines/form', locals: { machine: @machine } %>
<% else %>
  <%= turbo_stream.update 'new_machine', partial: 'machines/new_machine_link' %>
  <%= turbo_stream.prepend 'machines', partial: 'machines/machine', locals: { machine: @machine }  %>
<% end %>

app/views/machines/edit.html.erb
<% content_for :title, "Editing machine" %>

<h1>Editing machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Show this machine", @machine %> |
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/edit.turbo_stream.erb
<%= turbo_stream.update dom_id(@machine), partial: 'machines/form', locals: { machine: @machine } %>

app/views/machines/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Machines" %>

<h1>Machines</h1>

<div id="new_machine">
    <%= render partial: 'machines/new_machine_link' %>
</div>

<div id="machines">
  <% @machines.each do |machine| %>
    <%= render machine %>
  <% end %>
</div>

app/views/machines/new.html.erb
<% content_for :title, "New machine" %>

<h1>New machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/new.turbo_stream.erb
<%= turbo_stream.update 'new_machine', partial: 'machines/form', locals: { machine: @machine } %>

app/views/machines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @machine %>

<div>
  <%= link_to "Edit this machine", edit_machine_path(@machine) %> |
  <%= link_to "Back to machines", machines_path %>

  <%= button_to "Destroy this machine", @machine, method: :delete %>
</div>

app/views/machines/update.turbo_stream.erb
<% if @machine.errors.present? %>
  <%= turbo_stream.update dom_id(@machine), partial: 'machines/form', locals: { machine: @machine } %>
<% else %>
  <%= turbo_stream.update dom_id(@machine), partial: 'machines/machine', locals: { machine: @machine }  %>
<% end %>